# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 00:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(7)])),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('school', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
